### ISSUE TITLE
Inspirational Front-ends

### ISSUE THREAD

**Issue by ethanvernon** [chingu-voyages/v9-bears-team-30#10]
- https://eldoradoweather.com/climate/world-extremes/world-temp-rainfall-extremes.php
^ maybe use charts

- https://eldoradoweather.com/forecast/world-forecasts/world-temperatures.html
^ not very attractive

- https://www.strava.com/heatmap#7.00/-120.90000/38.36000/hot/all
^ different data, but nice map, nice presentation; responsive, my favorite

- https://www.meteoblue.com/en/weather/map/maxmintemp/north-america
^ another option

**Comment by willjw3** [comment]
Looks like some good stuff. I'll take a deeper look this weekend.
