### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ethanvernon** [chingu-voyages/v9-bears-team-30#11]
Minimum needing to start getting users:
- sign up page
- landing page with project description

**Comment by willjw3** [comment]
What about having minimal instructions and immediate functionality on the landing page? For example, we could have a world map that displays the top X hot spots, and then below we could have some select components and input fields for filtered queries. Then we could have an 'About' page for those who want to know more about the project, usage, etc,... ?

How much do we want to give users who sign up? A complete profile? Or just the bare minimum, including saved searches and such?
